### PR TITLE
Hotfix/build refactoring

### PR DESCRIPTION
**Pull request by kapecp**
otestovat a mergnut

### CODE REVIEW

**Comment by cimox** [comment]
Stale dostavam tuto chybu:

```
/Users/cimo/_TP/3dsoftviz/src/main.cpp:22: error: 'easylogging++.h' file not found
#include "easylogging++.h"
         ^
```

V dependecies mam easyloggingpp (`git submodule update --init --recursive` som spustil).

**Comment by cimox** [comment]
Po fixe, ktory som pushol, na OSX vsetko OK.

**Comment by kapecp** [comment]
som zvedavy, kto a kedy pride na to, ze to pod Win asi nebude fungovat...

**Comment by cimox** [comment]
Kvoli tej relativnej ceste k noiseutils?

**Comment by illesD** [comment]
asi to bude kvôli tomuto:
For other releases, please visit releases page. If you application does not support C++11, please consider using v8.91. This is stable version for C++98 and C++03, just lack some features.
(https://github.com/easylogging/easyloggingpp/tree/v8.91)

tu s tým aj majú problémy:
https://github.com/easylogging/easyloggingpp/issues/243

**Comment by kapecp** [comment]
fajn, ze to funguje, ale principialne je to zle, lebo -DOSG_LIBRARY_STATIC hovori, ze sa ma staticky linkovat na OSG, co iste nerobime.... nieco je zle na Win - mozno ako je zbuildene OSG

nechame to tak (inde to nevadi), ale upravte to na 

if( MSVC )
list( APPEND ALL_COMPILE_DEFINITIONS -DOSG_LIBRARY_STATIC)
endif()

**Comment by kapecp** [comment]
este nemergovat! par veci idem upravit

**Comment by kapecp** [comment]
ok, otestovat a mergnut

**Comment by cimox** [comment]
Na OSX vsetko OK, mozem mergnut?

**Pull request merged**
