### PR TITLE
Hotfix select fixes

### PR DESCRIPTION
**Pull request by IceHax**
Contains node refactor & node select fix (from garajm) + edge select fix

### CODE REVIEW

**Comment by kapecp** [comment]
ako bol spraveny commit 08f5a54 ???

**Comment by IceHax** [comment]
Z https://github.com/garajm/RealityNotFound/tree/develop 
som skopiroval zmeny ktore suviseli s refactorom nodov a opravou oznacovania , minimum aby to fungovalo.

**Comment by cimox** [comment]
Co stymto? Na OSX vyzera, ze to funguje ako ma.

**Comment by IceHax** [comment]
https://github.com/cimox/3dsoftviz/pull/15/commits

**Pull request closed without merging**
